### PR TITLE
Reorganized for bower and npm

### PR DESCRIPTION
**Pull request by stopspazzing**
Reorganized everything so could be used with bower and npm. No bower or npm packages were created or setup, just first initial pre-setup.

### CODE REVIEW

**Comment by stopspazzing** [comment]
Please review and take a look. If this is correct would fix issue 23. All that needs to be done is create the bower and npm packages aka register them. I am unsure if this would work or not, because never set up anything for bower or npm before, used another github project as an example for both.

**Comment by dominic-p** [comment]
Thanks for putting this together. I don't use npm or bower in my workflow, but looking at the files, I see references to a `dist` directory. However, there isn't one in your fork. I imagine you would store the minified js and css files there. Do you know if that's required for the package managers to work properly? Is it possible to test this in anyway before I merge it?

**Comment by stopspazzing** [comment]
I'm not 100% sure the answer to the last 2 questions, I can find out tho. I do use bower and npm so I can test it if it is possible. I'll find out and let you know. :)

**Comment by dominic-p** [comment]
Thanks for checking on that. Pleas let me know how the testing goes. Looking at videojs-youtube, it looks like they have an automated build process setup that generates a `dist` folder which is included in their releases. I wonder if bower grabs the latest release or just the current master branch.

**Comment by stopspazzing** [comment]
Bower package works fine, still making sure puts files in right location.
```
bower install https://github.com/stopspazzing/videojs-resolution-selector.git
bower not-cached    https://github.com/stopspazzing/videojs-resolution-selector.git#*
bower resolve       https://github.com/stopspazzing/videojs-resolution-selector.git#*
bower checkout      videojs-resolution-selector#master
bower resolved      https://github.com/stopspazzing/videojs-resolution-selector.git#f649736f95
videojs-resolution-selector#f649736f95 bower_components/videojs-resolution-selector
└── video.js#4.12.6
```

**Comment by stopspazzing** [comment]
Bower is working great, now to test npm

**Comment by stopspazzing** [comment]
NPM is working without issues, should work fine once committed. Need to be added to npm registry so people can grab it globally, still trying to figure out this command, has to be run from folder of package with package.json in it.

**Comment by dominic-p** [comment]
Alright, this is looking pretty good. I'll go ahead and pull it in and register the package with NPM and Bower. Feel free to make additional pull requests with recommended tweaks to the package management systems as they are needed.

Thanks for taking the time to get this working.

**Pull request merged**
